services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    container_name: assa_abloy_lock_simulator_postgres_db
    environment:
      POSTGRES_DB: assa_abloy_lock_simulator
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
    name: assa_abloy_lock_simulator_postgres_db_postgres_data