spring:
  application:
    name: interview

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc://postgresql:localhost:5432/assa_abloy_lock_simulator
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${aws.cognito.uri}/.well-known/jwks.json

      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/oauth/callback
            scope:
              - email
              - openid
              - phone
        provider:
          cognito:
            authorization-uri: https://us-east-19brfo1qri.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://us-east-19brfo1qri.auth.us-east-1.amazoncognito.com/oauth2/token
            user-info-uri: https://us-east-19brfo1qri.auth.us-east-1.amazoncognito.com/oauth2/userInfo
            jwk-set-uri: ${aws.cognito.uri}/.well-known/jwks.json

aws:
  accessKeyId: ${ACCESS_KEY_ID}
  secretKey: ${SECRET_KEY}
  region: us-east-1
  cognito:
    uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_9BrFO1qrI
    revoke-token-uri: https://us-east-19brfo1qri.auth.us-east-1.amazoncognito.com/oauth2/revoke