spring:
  application:
    name: interview

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_password}
    url: jdbc://postgresql:localhost:5432/assa_abloy_lock_simulator
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${aws.cognito.uri}/.well-known/jwks.json

      client:
        registration:
          cognito:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid
        provider:
          cognito:
            issuer-uri: ${aws.cognito.uri}

aws:
  accessKeyId: ${ACCESS_KEY_ID}
  secretKey: ${SECRET_KEY}
  region: us-east-1
  cognito:
    uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_WH9sgrlAo
    user-pool-id: us-east-1_WH9sgrlAo

  default-users:
    reader:
      email: ${READER_USER_EMAIL}
      password: ${READER_USER_PASSWORD}
      phone: ${READER_USER_PHONE}
    writer:
      email: ${WRITER_USER_EMAIL}
      password: ${WRITER_USER_PASSWORD}
      phone: ${WRITER_USER_PHONE}
