### Get all Gateways
GET {{baseUrl}}/api/gateways
Accept: application/json
Authorization: Bearer {{accessToken}}


### Get Gateway by Serial
GET {{baseUrl}}/api/gateways/ALKG000000000606
Accept: application/json
Authorization: Bearer {{accessToken}}


### Create a new Gateway
POST {{baseUrl}}/api/gateways
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "serial": "ALKG000000000606",
  "macAddress": "11:22:33:44:55:66",
  "version": "v4.0.0"
}


### Update an existing Gateway
PUT {{baseUrl}}/api/gateways/ALKG000000000606
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "serial": "ALKG000000000606",
  "macAddress": "11:22:33:44:55:66",
  "online": true,
  "version": "v4.1.0"
}


### Delete a Gateway
DELETE {{baseUrl}}/api/gateways/ALKG000000000606
Authorization: Bearer {{accessToken}}
