### Register user
POST {{baseUrl}}/api/oauth/signup
Content-Type: application/json
Accept: application/json

{
  "email": "lhpetrola@gmail.com",
  "phoneNumber": "+5561999387022",
  "password": "c@I2809P3]7"
}


### Login writer User
POST {{baseUrl}}/api/oauth/login
Content-Type: application/json
Accept: application/json

{
  "email": "bibica.bassambeth@hotmail.com",
  "password": "c@I2809P3]7"
}


### Login reader User
POST {{baseUrl}}/api/oauth/login
Content-Type: application/json
Accept: application/json

{
  "email": "lhpetrola@gmail.com",
  "password": "c@I2809P3]7"
}


### Get authenticated data
GET {{baseUrl}}/api/oauth/me
Authorization: Bearer {{accessToken}}


### Email validation
POST {{baseUrl}}/api/oauth/validate-email?email=lhpetrola@gmail.com&code=733393


### Resend email validation code
POST {{baseUrl}}/api/oauth/resend-email-validation-code?email=lhpetrola@gmail.com


### Revoke User role
PUT {{baseUrl}}/api/oauth/revoke-user-role?email=lhpetrola@gmail.com
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "roles": [
    {
      "role": "WRITER"
    }
  ]
}



### Grant User role
PUT {{baseUrl}}/api/oauth/grant-user-role?email=lhpetrola@gmail.com&role=WRITER
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "roles": [
    {
      "role": "WRITER"
    }
  ]
}
