### Register User
POST http://localhost:8080/oauth/register
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{access_token}}

{
  "email": "lhpetrola@gmail.com",
  "password": "c@I2809P3]7"
}

### Login Writer User
POST http://localhost:8080/oauth/login
Content-Type: application/json
Accept: application/json

{
  "email": "bibica.bassambeth@hotmail.com",
  "password": "c@I2809P3]7"
}

### Login Reader User
POST http://localhost:8080/oauth/login
Content-Type: application/json
Accept: application/json

{
  "email": "lhpetrola@gmail.com",
  "password": "c@I2809P3]7"
}

### Get Authenticated data
GET http://localhost:8080/oauth/me
Authorization: Bearer {{access_token}}

### Email confirm
POST http://localhost:8080/oauth/confirm-email?email=lhpetrola@gmail.com.com&code=122052

### Resend Email confim code
POST http://localhost:8080/oauth/resend-email?email=lhpetrola@gmail.com

### Change Role User
GET http://localhost:8080/oauth/change-role?email=lhpetrola@gmail.com&role=WRITER
Authorization: Bearer {{access_token}}
