### Get All Users
GET {{baseUrl}}/api/users
Accept: application/json
Authorization: Bearer {{accessToken}}


### Get User by Email
GET {{baseUrl}}/api/users/by-email/lhpetrola@gmail.com
Accept: application/json
Authorization: Bearer {{accessToken}}
