### Get all Locks
GET http://localhost:8080/api/locks
Accept: application/json

###

### Get Lock by Serial
GET http://localhost:8080/api/locks/ALKS000000000999
Accept: application/json

###

### Create a new Lock
POST http://localhost:8080/api/locks
Content-Type: application/json

{
  "serial": "ALKS000000000999",
  "name": "Test Lock 999",
  "macAddress": "AA:BB:CC:DD:EE:FF",
  "connected": true,
  "version": "v3.0.0"
}

###

### Update an existing Lock
PUT http://localhost:8080/api/locks/ALKS000000000999
Content-Type: application/json

{
  "serial": "ALKS000000000999",
  "name": "Updated Lock Name",
  "macAddress": "AA:BB:CC:DD:EE:FF",
  "connected": false,
  "version": "v3.1.0"
}

###

### Delete a Lock
DELETE http://localhost:8080/api/locks/ALKS000000000999
